### ISSUE TITLE
Disable express functions that don't exist in fastify

### ISSUE THREAD

**Issue by abenhamdine** [fastify/fastify-benchmarks#4]
To ensure a better comparison between frameworks, it would be interesting to disable some Express functions that don't exist in fastify, for example Etag generation, see the comment of Doug Wilson here : https://github.com/abenhamdine/frameworks-benchmark/issues/3

**Comment by cagataycali** [comment]
We need to make a comparison between fastify and the Express by default. 
In the meantime, we can get a more realistic result by turning off the extra features added to Express's standard.

I'll write another test to see the difference between the two cases, is there a list showing which features I can turn off by speeding up Express.js?

@dougwilson @abenhamdine

**Comment by dougwilson** [comment]
The various features with on/off flags are just at http://expressjs.com/en/4x/api.html#app.set and there isn't that much.

The main thought is that if the Fastify app is using the schema declaration (https://github.com/fastify/fastify-benchmarks/blob/574f04b32faea9689131a1d8510b5096cdaaa4cc/benchmarks/fastify.js#L3) then why not turn off the ETag generation in the Express app? Or alternatively just not use the schema in the Fastify app so they are similar to what a first-time user would just write off the shelf if that is the goal.

I'm not here at all to claim that Express is faster than Fastify or anything; I really don't care to do microbenchmarks. It was more of just a general question, especially with the ETag being such a perf hit.

The biggest issue in general is that these kind of benchmarks lead frameworks to just strip down all the useful but default-on features to just default them to off in order to make them look good in the benchamrks that just compare a hello world without feature parity.

Express will eventually allow turning off all the conditional responses (i.e. 304 Not Modified) which helps as well, but of course the reason ETags/conditional responses are on by default is because we feel like the bandwidth savings are more important than having the slimmest possible profile for micro benchmarks.

**Comment by cagataycali** [comment]
I fully agree with your words. I will be working on a test that includes details of the pluses and minuses

**Comment by mcollina** [comment]
This is a good one. However, I would keep the two versions, and maybe add one without the fast-json-schema serializer.

@dougwilson thanks for checking this out. Express is amazing :) and thanks for all the work there.

**Comment by abenhamdine** [comment]
FWIW, keeping the two versions is also the approach used by techempowered benchmarks (see https://www.techempower.com/benchmarks/#section=data-r14&hw=ph&test=json&b=2&l=8vn01r&a=2  
and see  "Implementation approach" : 

![image](https://user-images.githubusercontent.com/7466144/30249545-defd70b8-963e-11e7-9b1b-37314209a40a.png)

**Comment by dougwilson** [comment]
Right, but something happened recently where for the last few days I haven't been able to work on Express; rather I have been bombarded with questions about this project and the benchmarks. This seems to happen every so often, particularly when a framework specifically says it is faster.

I rather ship a gimped and stripped down Express 5 so I don't have to keep going though this exercise if benchmarks not turning off the heavy features of Express than ship a better out of the box Express.

Please I love you guys and it hurts me to see you contributing to the situation.
